ACCEPTED_PROFILE_COLUMNS = [
    "id",
    "loan_amnt",
    "funded_amnt",
    "term",
    "int_rate",
    "installment",
    "grade",
    "sub_grade",
    "emp_length",
    "home_ownership",
    "annual_inc",
    "verification_status",
    "issue_d",
    "loan_status",
    "purpose",
    "addr_state",
    "dti",
    "fico_range_low",
    "fico_range_high",
    "inq_last_6mths",
    "delinq_2yrs",
    "open_acc",
    "revol_bal",
    "revol_util",
    "total_acc",
    "tot_cur_bal",
    "percent_bc_gt_75",
    "bc_util",
    "mths_since_recent_inq",
    "pub_rec_bankruptcies",
    "pct_tl_nvr_dlq",
    "out_prncp",
    "total_pymnt",
    "total_rec_prncp",
    "total_rec_int",
    "recoveries",
    "last_pymnt_d",
    "earliest_cr_line",
]

REJECTED_PROFILE_COLUMNS = [
    "Amount Requested",
    "Application Date",
    "Loan Title",
    "Risk_Score",
    "Debt-To-Income Ratio",
    "Zip Code",
    "State",
    "Employment Length",
    "Policy Code",
]